version: '3.8'

services:
  solidarize:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FUNCTIONS_WORKER_RUNTIME: "dotnet"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 125M
    ports:
      - 7071:80
    networks:
      - solidarize

networks:
  solidarize: