version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../src/SolidarizeFunctions/.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - solidarize

volumes:
  postgres-data:

networks:
  solidarize:
