version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../src/SolidarizeFunctions/.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

volumes:
  postgres-data:
